# Generated by Django 5.0.6 on 2024-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_goods', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(to='add_goods.category'),
        ),
    ]
